POST http://parking.msuproject.net/webservice/register
Content-Type: application/json
Cache-Control: no-cache

{
  "Name" :"pppporJaJA",
  "lastName" :"jaja",
  "email" :"pppp@gmail.com",
  "phone" :"0804795359",
  "password" : 12342364
}

<> 2562-07-29T050813.200.json

###

