POST http://parking.msuproject.net/webservice/parkingspot
Content-Type: application/json
Cache-Control: no-cache

{
  "parkingSpotName" :"จุดจอดที่ 2",
  "status" :"ใช้งาน",
  "activeOrInactive" :"ว่าง",
  "distance" :"33",
  "parkingID" : 4
}

###

